[package]
name = "websocket-client"
version = "0.1.0"
authors = ["james <alphafoobar@users.noreply.github.com>"]
edition = "2018"

[dependencies]
websocket = "0.23.0"
serde_json = "1.0.41"
chrono = "0.4.9"
openssl = "0.10.24"